config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#landing'

  post 'charges/new/:id' => 'charges#new', as: 'new_charge'

  resources :subscriptions
  resources :contests
  resources :charges

  match '/home',    to: 'pages#home',    via: 'get'
  match '/about',   to: 'pages#about',   via: 'get'
  match '/contact', to: 'pages#contact', via: 'get'

end

app/models/charge.rb
class Charge < ActiveRecord::Base

	attr_accessor :stripe_card_token

	belongs_to :contest
	belongs_to :user

	def save_with_payment(charge)
	  if valid?
	    charge = Stripe::Charge.create(
	      :amount => (charge.amount.to_i)*100,
	      :currency => "usd",
	      :card => stripe_card_token)
	    self.stripe_charge_token = charge_id
	    save!
	  end
	rescue Stripe::InvalidRequestError => e
	  logger.error "Stripe error while creating customer: #{e.message}"
	  errors.add :base, "There was a problem with your credit card."
	  false
	end

end

app/models/contest.rb
class Contest < ActiveRecord::Base
	
dragonfly_accessor :image
has_many :charges
belongs_to :user

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :contests
  has_many :charges
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	  @contest = Contest.find(params[:id])
	  @charge = Charge.new(amount: params[:amount])
	end

	def create
	  @charge = Charge.new(charges_params)
	  if @charge.save_with_payment(@charge)
	    redirect_to root_path, :notice => "Contribution was recorded succesfully!"
	  else
	    redirect_to root_path, :notice => "Transaction was not able to be recorded"
	  end
	end

	def charges_params
		params.require(:charge).permit(:stripe_card_token, :contest_id, :user_id, :amount)
	end

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController


  def index
    @contests = Contest.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 9)
  end

  def show
    @contest = Contest.find(params[:id])
  end

  def new
    @contest = Contest.new
  end

  def create
  	@contest = Contest.new(contest_params) 
  	if @contest.save
      flash[:success] = "Contest created successfully!"
  		redirect_to @contest
  	else
      flash[:danger] = "Contest could not be created"
  		redirect_to new_contest_path
  	end
  end

  def edit
  end

  def update
  end

  def destroy
  end


  def contest_params
  	params.require(:contest).permit(:title, :description, :image)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def landing
		@subscription = Subscription.new
		@ready = true
	end

	def home
		@subscription = Subscription.new
	end

	def about
	end

	def contact
	end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

	def new
		@subscription = Subscription.new
	end

	def create
		@subscription = Subscription.new(subscription_params)
		if @subscription.save
	      	flash[:success] = "You've been signed up! We will let you know when we are ready to launch!"
			redirect_to root_path
		else
			flash[:danger] = "Could not subscribe"
	  		redirect_to root_path
	  	end
	end


	def subscription_params
    	params.require(:subscription).permit(:fname, :lname, :email) 
   	end


end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Krowdprize"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/charges/_form.html.erb
<% content_for :head do %>
	<%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
<% end %>
<%= form_for @charge do |f| %>
	<div class="form-inputs">
		<div class="row">
			<%= f.hidden_field :contest_id  %>
			<%= f.hidden_field :user_id %>
			<%= f.hidden_field :amount %>
			<%= f.hidden_field :stripe_card_token %>
			<div class="small-12 medium-6 large-2 columns">
				<%= f.label "Amount:" %>
			</div>
			<div class="small-12 medium-6 large-10 columns" style="margin-bottom: 0.5rem; margin-top: 0.5rem;">
				<%= number_to_currency(@charge.amount, :unit => "$") %>
			</div>
			  <div class="small-12 medium-6 large-2 columns">
			    <%= label_tag :card_number, "Credit Card Number:" %>
			  </div>
			  <div class="small-12 medium-6 large-10 columns">
			    <%= text_field_tag :card_number, nil, name: nil %>
			  </div>
			  <div class="small-12 medium-6 large-2 columns">
			    <%= label_tag :card_code, "Security Code on Card (CVV):" %>
			  </div>
			  <div class="small-12 medium-6 large-10 columns end">
			    <%= text_field_tag :card_code, nil, name: nil%>
			  </div>
			  <div class="small-12 medium-6 large-2 columns">
			    <%= label_tag :card_month, "Card Expiration:" %>
			  </div>
			  <div class="small-6 medium-3 columns">
			    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
			  </div>
			  <div class="small-6 medium-3 columns">
			    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
			  </div>
			
			<div id="stripe_error">
			  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
			</div>
			
		</div>
		<div class="row">
			<div class="form-actions small-9 small-offset-2 columns">
				<%= f.submit "Donate" %>
			</div>
		</div>
	</div>
<% end %>
<% content_for :js do %>
    <%= javascript_include_tag "https://js.stripe.com/v1", "application" %> 
	<%= javascript_include_tag asset_path("stripe/stripe.js"), "application" %>
<% end %>

app/views/charges/index.html.erb
<h2>Thanks, you paid blah blah blah </h2> this is charges index page

app/views/charges/new.html.erb
<%= provide(:title, 'Donate to ' + @contest.title) %>
<br />

asgfadsgdsfasdfsda
<div class="row">
	<div class="small-12 columns">
		<h1>Donate to: <%= @contest.title %></h1>
		<br />
		<%= render 'form' %>
		<%= link_to 'Cancel', :back %>
	</div>
</div>
<br />
<br />

app/views/charges/show.html.erb
this is charges show page

app/views/contests/_contest_form.html.erb
<%= form_for @contest, :html => { :role => 'form', :class => 'new-contest-form', :multipart => true } do |f| %>

	<div class="form-inputs">
		<div class: "form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control", placeholder:"Type your update title here" %>
		</div>
		<div class: "form-group">
		<%= f.label :description %>
	    <%= f.text_field :description, class: "form-control", placeholder:"Type your update here" %>
		</div>
		<div class: "form-group">
		<%= f.label :image %>
		<%= f.file_field :image %>
		</div>
	</div>
	
	<div class="form-actions">
	  <%= f.button :submit, class: "btn btn-default btn-lg" %>
	</div>

<% end %>


</div>

app/views/contests/edit.html.erb
This is edit contests page

app/views/contests/index.html.erb
This is is Index contests page
<div class="container contest-index-container">

	<div id="contest-tiles" class="transitions-enabled">
	  <% @contests.each do |contest| %>
		<div class="box panel panel-default">
			<%= image_tag contest.image.thumb('400x500#').url unless contest.image.nil? %>
			<div class="panel-body">
				<p><strong><%= contest.title %></strong></p>
				<p><%= contest.description %></p>
			</div>
		</div>
	  <% end %>        
	</div>

	<div class="contest-paginate">
	  <%= will_paginate @contests, renderer: BootstrapPagination::Rails %>
	</div>

</div>

app/views/contests/new.html.erb
<%= provide(:title, 'Create A New Contest') %>
<br />
<div class="row">
	<div class="new-contest-container">
		<h1>Create a new contest</h1>
		<br />	
		<%= render 'contest_form' %>
	</div>
</div>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

app/views/contests/show.html.erb
<% provide(:title, @contest.title) %>
<div class="container contest-show-container">

	<div class="contest-name">
        <%= @contest.title %> 
  	</div>
  	
  	<div class="i-tabs">
  		<ul class="nav nav-tabs">
  			<li><%= link_to "Story", '#' %></li>
	        <li><%= link_to "Updates", '#' %></li>
	        <li><%= link_to "Comments", '#' %></li>
	        <li><%= link_to "Funders", '#' %></li>
	        <li><%= link_to "Gallery", '#' %></li>
	        <li><%= link_to "Random", '#' %></li>
	  	</ul>
  	</div>
  		
	<div class="col-md-8 col-sm-8 contest-show-content">
	  <div class="contest-show-content2">

		<div class="contest-image">
    		<%= image_tag @contest.image.thumb('600x320').url if @contest.image_stored? %>
    	</div>

    	<div class="contest-description">
        	<%= @contest.description %>
    	</div>
     </div>
    </div>

    <div class="col-md-4 col-sm-4">

    		<%= form_tag new_charge_path(@contest), :method => "post", :role => "form", :class => "donate-form" do %>

				<div class="form-group">
					<label>Any amount more that $1</label>
					$<%= text_field_tag :amount, "25", :class => "form-control" %>
				</div>
						
				<div class="button container">
					<%= button_tag "Donate", :class => "btn btn-default btn-lg" %>
				</div>
			<% end %>

    </div>

</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="bottom-container">
      <div class="container-fluid">
        <div class="random">

                <div class="row footer-row">
                    <div class="footer-box col-sm-12">
                        <div class="social-links">
                            <%= link_to image_tag('mail-white.png', id: 'blah', class: 'footer-img', alt: 'About'), 'contact_path' %>
                            <%= link_to image_tag('facebook-white.png', id: 'blah', class: 'footer-img', alt: 'About'), 'https://www.facebook.com/krowdprize' %>
                            <%= link_to image_tag('twitter-white.png', id: 'blah', class: 'footer-img', alt: 'About'), 'https://twitter.com/Krowdprize' %>
                        </div>
                    </div>
              
               </div>

      </div>
    </div>


                  <div class="bottom">
                      <p>© 2014 Krowdprize</p>
                  </div>


  </div>

</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand">KrowdPrize<%#= image_tag('KrowdPrizeLogoNew3.jpg') %></a>
    </div>
    

    <% unless @ready %>
    <div class="navbar-container-right">
      
      <ul class="nav nav-pills navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "About",    about_path %></li>
        <li><%= link_to "Contact",    contact_path %></li>
        <li>  
            <% if current_user.present? %>
                <%= link_to 'Sign Out',destroy_user_session_path, :method => :delete %>
            <% else %>
                <%= link_to 'Sign In', new_user_session_path %>
        </li>
        <li><%= link_to 'Register Now!', new_user_registration_path %><% end %></li>
      </ul>

    </div>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "https://js.stripe.com/v1/", "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>
  
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      
        <%= yield %>

      <%= render 'layouts/footer' %>
  
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
	  <%= yield %>
	</body>
</html>

app/views/pages/about.html.erb
This is About page

app/views/pages/contact.html.erb
This is contact page

app/views/pages/home.html.erb

<!-- Banner -->

<div class="banner">
  <div class="banner-content">

		<div class='logo-image'>
		<%= image_tag("logo.png", alt: "logo-image", class:'img-responsive logo') %>
		</div>

		<div class='opening-text'>
			<span class="opening-text-name">Krowdprize</span> The Platform For World-changing Crowdfunded Contests
		</div>
		<div class="sub-opening-text"> 
			Incentivizing human progress one contest at a time 
		</div>


  </div>
</div>

<!-- Features -->

<div class="big-container">

<div class="container-fluid">

    <div class="mid-text-container">
        <h1>We create kick-ass contests</h1>
          <p>Competition is the best way to incentivize progress</p>
    </div>


    <div class="row">

        <div class="service-box col-sm-4">
            <div class="square animated bounceIn">
                <%= image_tag('profile.png', id: 'blah', class: 'media-img', alt: 'About') %>
            </div>
            <h2>
                Community
            </h2>
            <p>
                Creates contests and vote for your favorite ones
            </p>
        </div>

        <div class="service-box col-sm-4">
            <div class="square animated bounceIn">
                <%= image_tag('nudge.png', class: 'media-img', alt: 'About') %>
            </div>
            <h2>
                Funding
            </h2>
            <p>
                Crowdfund prize money and get the top contests up and running  
            </p>
        </div>

        <div class="service-box col-sm-4">
            <div class="square animated bounceIn">
                <%= image_tag('getnoticed.png', class: 'media-img', alt: 'About') %>
            </div>
            <h2>
                Competition
            </h2>
            <p>
                Browse contests and compete for the top prizes
            </p>
        </div>


    </div>

</div>

</div>


<!-- signup form -->

<div class="subscription-section">

    <div class="container-fluid">

        <div class="row">

            <div class="newsletter-form-img col-md-4 col-lg-6">
                <div class="container-form-image">
                    <%= image_tag('email.png', class: 'subscription-img', alt: 'subscription-image') %>
                </div>
            </div>

            <div class="newsletter-form-content col-md-8 col-lg-6">
                <p>Sign Up For Free</p>
                <p>Get early access to the revolutionary platform</p>
            
                    <div class="form-subscribe">
                        <%= form_for(@subscription, { :class => 'form-horizontal' }) do |f|  %>

                            <div class="form-inputs subscription-box">
                                <div class: "form-space">
                                    <div class: "form-group">
                                        <%= f.text_field :fname, class: "form-control sub-field", placeholder: "First Name" %>
                                    </div>
                                </div>
                                <div class: "form-space">
                                    <div class: "form-group">
                                        <%= f.text_field :lname, class: "form-control sub-field", placeholder:"Last Name" %>
                                    </div>
                                </div>
                                <div class: "form-space">
                                    <div class: "form-group">
                                        <%= f.email_field :email, class: "form-control sub-field", placeholder:"Email" %>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                              <%= f.button :submit, class: "btn btn-default"%>
                            </div>

                        <% end %>

                    </div>
            </div>



        </div>

    </div>

</div>



<!-- imagebreak -->

<div class="image-break">
    <div class="mid-text-container">
        <h1><b>Contests have proven to be the most effective way to incentivize innovation</b></h1>
          <p><b>Below are some of our favorite examples</b></p>
    </div>

</div>
<!--- Examples -->

<div class="example-section">


    <div class="container-fluid">

        <div class="row">

            <div class="example-img col-md-4 col-lg-6">
                <div class="container-example-image">
                    <%= image_tag('airplane3.png', class: 'example-img', alt: 'example-image') %>
                </div>
            </div>

            <div class="example-content col-md-8 col-lg-6">
                <h1>Aviation: The Oertig Prize</h1>
                <h3>$25,000 reward ($340,067 as of 2014) offered on May 19, 1919, NYC</h3>
                </br>
                </br>
                <p>
                American Charles Lindbergh completed the first ever cross-atlantic flight flying from New York to Paris in 1927. He became famous world-wide for his achievements. Public interest in air travel bloomed and the aviation industry was born.    
                </p>
            </div>

        </div>
    </div>

</div>

<div class="example-section2">

    <div class="container-fluid">
        <div class="row">

            <div class="example-content2 col-md-8 col-lg-6">
                 <h1>Food Preservation: The Napoleonic Wars Prize</h1>
                    <h3>12,000 Fracs reward offered by the french government</h3>
                    </br>
                    </br>
                    <p>
                    Napoleon offered 12,000 francs to improve upon the prevailing food preservation methods of the time. Not surprisingly, the purpose was to better feed his army "when an invaded country was not able or inclined to sell or provide food". Fifteen years later, confectioner Nicolas François Appert claimed the prize. He devised a method involving heating, boiling and sealing food in airtight glass jars — the same basic technology still used to can foods.    
                    </p>
            </div>

            <div class="example-img2 col-md-4 col-lg-6">
                <div class="container-example-image2">
                    <%= image_tag('food3.png', class: 'example-img2', alt: 'example-image2') %>
                </div>
            </div>

        </div>
    </div>

</div>

<div class="example-section">

    <div class="container-fluid">
        <div class="row">

            <div class="example-img col-md-4 col-lg-6">
                <div class="container-example-image">
                    <%= image_tag('cloud.png', class: 'example-img', alt: 'example-image') %>
                </div>
            </div>

            <div class="example-content col-md-8 col-lg-6">
                    <h1>Netflix Prize</h1>
                    <h3>$1,000,000 open competition for the best collaborative filtering algorithm to predict user ratings for films</h3>
                    </br>
                    </br>
                    <p>
                    the grand prize of US$1,000,000 was given to the BellKor's Pragmatic Chaos team which bested Netflix's own algorithm for predicting ratings by 10.06%  
                    </p>
            </div>

        </div>
    </div>

</div>

app/views/pages/landing.html.erb

<!-- Banner -->

<div class="banner">
  <div class="banner-content">

		<div class='logo-image'>
		<%= image_tag("logo.png", alt: "logo-image", class:'img-responsive logo') %>
		</div>

		<div class='opening-text'>
			<span class="opening-text-name">Krowdprize</span> The Platform For World-changing Crowdfunded Contests
		</div>
		<div class="sub-opening-text"> 
			Incentivizing human progress one contest at a time 
		</div>


  </div>
</div>

<!-- Features -->

<div class="big-container">

<div class="container-fluid">

    <div class="mid-text-container">
        <h1>We create kick-ass contests</h1>
          <p>Competition is the best way to incentivize progress</p>
    </div>


    <div class="row">

        <div class="service-box col-sm-4">
            <div class="square animated bounceIn">
                <%= image_tag('profile.png', id: 'blah', class: 'media-img', alt: 'About') %>
            </div>
            <h2>
                Community
            </h2>
            <p>
                Creates contests and vote for your favorite ones
            </p>
        </div>

        <div class="service-box col-sm-4">
            <div class="square animated bounceIn">
                <%= image_tag('nudge.png', class: 'media-img', alt: 'About') %>
            </div>
            <h2>
                Funding
            </h2>
            <p>
                Crowdfund prize money and get the top contests up and running  
            </p>
        </div>

        <div class="service-box col-sm-4">
            <div class="square animated bounceIn">
                <%= image_tag('getnoticed.png', class: 'media-img', alt: 'About') %>
            </div>
            <h2>
                Competition
            </h2>
            <p>
                Browse contests and compete for the top prizes
            </p>
        </div>


    </div>

</div>

</div>


<!-- signup form -->

<div class="subscription-section">

    <div class="container-fluid">

        <div class="row">

            <div class="newsletter-form-img col-md-4 col-lg-6">
                <div class="container-form-image">
                    <%= image_tag('email.png', class: 'subscription-img', alt: 'subscription-image') %>
                </div>
            </div>

            <div class="newsletter-form-content col-md-8 col-lg-6">
                <p>Sign Up For Free</p>
                <p>Get early access to the revolutionary platform</p>
            
                    <div class="form-subscribe">
                       
                        <form action="http://krowdprize.us8.list-manage.com/subscribe/post" method="POST" role="form">

                            <div class="form-inputs subscription-box">

                                <input type="hidden" name="u" value="c50dae01481d495cdc2281893">
                                <input type="hidden" name="id" value="11a0543600">

                                <div class: "form-space">
                                    <div class: "form-group">
                                       <input type="text" name="MERGE1" id="MERGE1" class="form-control" size="25" value="" placeholder="First Name">
                                    </div>
                                </div>
                                <div class: "form-space">
                                    <div class: "form-group">
                                        <input type="text" name="MERGE2" id="MERGE2" class="form-control" size="25" value="" placeholder="Last Name">
                                    </div>
                                </div>
                                <div class: "form-space">
                                    <div class: "form-group">
                                        <input type="email" autocapitalize="off" autocorrect="off" name="MERGE0" id="MERGE0" class="form-control" size="25" value="" placeholder="Email">
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                              <input type="submit" class="btn btn-default btn-lg" name="submit" value="Sign up!">
                            </div>

                       

                    </div>
            </div>



        </div>

    </div>

</div>



<!-- imagebreak -->

<div class="image-break">
    <div class="mid-text-container">
        <h1><b>Contests have proven to be the most effective way to incentivize innovation</b></h1>
          <p><b>Below are some of our favorite examples</b></p>
    </div>

</div>
<!--- Examples -->

<div class="example-section">


    <div class="container-fluid">

        <div class="row">

            <div class="example-img col-md-4 col-lg-6">
                <div class="container-example-image">
                    <%= image_tag('airplane3.png', class: 'example-img', alt: 'example-image') %>
                </div>
            </div>

            <div class="example-content col-md-8 col-lg-6">
                <h1>Aviation: The Oertig Prize</h1>
                <h3>$25,000 reward ($340,067 as of 2014) offered on May 19, 1919, NYC</h3>
                </br>
                </br>
                <p>
                American Charles Lindbergh completed the first ever cross-atlantic flight flying from New York to Paris in 1927. He became famous world-wide for his achievements. Public interest in air travel bloomed and the aviation industry was born.    
                </p>
            </div>

        </div>
    </div>

</div>

<div class="example-section2">

    <div class="container-fluid">
        <div class="row">

            <div class="example-content2 col-md-8 col-lg-6">
                 <h1>Food Preservation: The Napoleonic Wars Prize</h1>
                    <h3>12,000 Fracs reward offered by the french government</h3>
                    </br>
                    </br>
                    <p>
                    Napoleon offered 12,000 francs to improve upon the prevailing food preservation methods of the time. Not surprisingly, the purpose was to better feed his army "when an invaded country was not able or inclined to sell or provide food". Fifteen years later, confectioner Nicolas François Appert claimed the prize. He devised a method involving heating, boiling and sealing food in airtight glass jars — the same basic technology still used to can foods.    
                    </p>
            </div>

            <div class="example-img2 col-md-4 col-lg-6">
                <div class="container-example-image2">
                    <%= image_tag('food3.png', class: 'example-img2', alt: 'example-image2') %>
                </div>
            </div>

        </div>
    </div>

</div>

<div class="example-section">

    <div class="container-fluid">
        <div class="row">

            <div class="example-img col-md-4 col-lg-6">
                <div class="container-example-image">
                    <%= image_tag('cloud.png', class: 'example-img', alt: 'example-image') %>
                </div>
            </div>

            <div class="example-content col-md-8 col-lg-6">
                    <h1>Netflix Prize</h1>
                    <h3>$1,000,000 open competition for the best collaborative filtering algorithm to predict user ratings for films</h3>
                    </br>
                    </br>
                    <p>
                    the grand prize of US$1,000,000 was given to the BellKor's Pragmatic Chaos team which bested Netflix's own algorithm for predicting ratings by 10.06%  
                    </p>
            </div>

        </div>
    </div>

</div>